/* Generated by Three Forma Styli. Do not edit. */
export const axes = {"theme":{"attribute":"data-theme-mode","modes":["dark","light"]},"size":{"attribute":"data-size-mode","modes":["regular","s","l"]}};
export const colors = ["bg","ev","ink","neu","pri","duo","shd"];
export const colorGroups = {"accents":["pri","duo"]};

/** A generated custom property as a CSS value: cssVar('clr-pri') → 'var(--clr-pri)'. */
export function cssVar(name) {
	return `var(--${name})`;
}
