/* Generated by Three Forma Styli. Do not edit. */
const roles = {"prose":{"sizes":["min","s","base","l","max"],"styles":["normal","italic"],"weights":["min","lo","hi","max"]},"heading":{"sizes":["min","s","base","l","max"],"styles":["normal"],"weights":["min","lo","hi","max"]},"label":{"sizes":["min","s","base","l","max"],"styles":["normal","italic"],"weights":["min","lo","hi","max"]}};

/** Class names for a role, size, style and weight. Pass the CSS Modules object to get module names. */
export function typographyClassName(selection, classes) {
	const role = roles[selection.role];
	if (!role) throw new Error(`Unknown typography role "${selection.role}".`);
	const size = selection.size ?? 'base';
	if (!role.sizes.includes(size)) throw new Error(`Role "${selection.role}" has no size "${size}".`);
	const keys = [size === 'base' ? selection.role : `${selection.role}-${size}`];
	if (selection.fontStyle !== undefined) {
		if (!role.styles.includes(selection.fontStyle)) throw new Error(`Role "${selection.role}" has no style "${selection.fontStyle}".`);
		keys.push(`${selection.role}-style-${selection.fontStyle}`);
	}
	if (selection.weight !== undefined) {
		if (!role.weights.includes(selection.weight)) throw new Error(`Role "${selection.role}" has no weight "${selection.weight}".`);
		keys.push(`${selection.role}-weight-${selection.weight}`);
	}
	return keys.map((key) => (classes ? classes[key] : `text--${key}`)).join(' ');
}
