/* Generated by Three Forma Styli. Do not edit. */
export type TypographySelection =
	| {
			readonly role: "prose";
			readonly size?: "min" | "s" | "base" | "l" | "max";
			readonly fontStyle?: "normal" | "italic";
			readonly weight?: "min" | "lo" | "hi" | "max";
	  }
	| {
			readonly role: "heading";
			readonly size?: "min" | "s" | "base" | "l" | "max";
			readonly fontStyle?: "normal";
			readonly weight?: "min" | "lo" | "hi" | "max";
	  }
	| {
			readonly role: "label";
			readonly size?: "min" | "s" | "base" | "l" | "max";
			readonly fontStyle?: "normal" | "italic";
			readonly weight?: "min" | "lo" | "hi" | "max";
	  };

export type TypographyRole = TypographySelection['role'];

/** Class names for a role, size, style and weight. Pass the CSS Modules object to get module names. */
export declare function typographyClassName(
	selection: TypographySelection,
	classes?: Readonly<Record<string, string>>
): string;
