import { describe, expect, it } from 'vitest';
import os from 'node:os';
import path from 'node:path';
import fs from 'fs-extra';
import {
	commitPreparedFiles,
	assertPortableFontOutputName,
	assertNonOverlappingPreparedFaces,
	assertWebEmbeddingAllowed,
	prepareFonts,
	renderFontFaceCss,
	type PreparedFontsManifest,
} from './prepare.js';

describe('renderFontFaceCss', () => {
	it('accepts useful filenames and rejects cross-platform filesystem hazards', () => {
		expect(() => assertPortableFontOutputName('Supreme #1 ü.woff2', 'font output')).not.toThrow();
		for (const name of ['Supreme?.woff2', 'CON.woff2', 'font.woff2.', 'font\\name.woff2']) {
			expect(() => assertPortableFontOutputName(name, 'font output')).toThrowError(
				'must use portable path segments'
			);
		}
	});

	it('emits variable ranges and longhand face descriptors', () => {
		const manifest: PreparedFontsManifest = {
			schemaVersion: 2,
			families: {
				supreme: {
					family: 'Supreme Variable',
					display: 'swap',
					license: {
						id: 'ITF-FFL',
						file: 'licenses/supreme.txt',
						webEmbeddingAllowed: true,
						webEmbeddingBasis: 'Written vendor consent dated 2026-07-21.',
						transformationsAllowed: false,
					},
					faces: [
						{
							source: { file: 'supreme.woff2', format: 'woff2', sha256: 'source-hash' },
							file: 'supreme.woff2',
							url: '/fonts/supreme.woff2',
							format: 'woff2',
							style: 'normal',
							weight: { min: 100, max: 800 },
							bytes: 30_000,
							sha256: 'hash',
							strategy: 'copy',
							version: '1.0',
							copyright: 'Test fixture',
							names: {
								family: 'Supreme Variable',
								subfamily: 'Regular',
								full: 'Supreme Variable Regular',
								postscript: 'SupremeVariable-Regular',
							},
							sourceStyle: {
								weight: 400,
								width: 5,
								italic: false,
								oblique: false,
								italicAngle: 0,
							},
							axes: { wght: { name: 'Weight', min: 100, default: 800, max: 800 } },
							namedInstances: {},
							metrics: {} as PreparedFontsManifest['families'][string]['faces'][number]['metrics'],
							coverage: { glyphs: 500, codePoints: 300 },
							features: ['kern'],
							embedding: {
								noEmbedding: false,
								viewOnly: false,
								editable: false,
								noSubsetting: false,
								bitmapOnly: false,
							},
							warnings: [],
						},
					],
				},
			},
		};

		const css = renderFontFaceCss(manifest);
		expect(css).toContain('font-family: "Supreme Variable";');
		expect(css).toContain('font-weight: 100 800;');
		expect(css).toContain('font-style: normal;');
		expect(css).toContain('font-display: swap;');
		const rebased = renderFontFaceCss(manifest, {
			includeHeader: false,
			resolveUrl: (face) => `../assets/${face.file}`,
		});
		expect(rebased).toContain('src: url("../assets/supreme.woff2") format("woff2");');
		expect(rebased).not.toContain('Generated by three-forma-styli');
	});

	it('emits a standards-correct static oblique angle descriptor', () => {
		const manifest: PreparedFontsManifest = {
			schemaVersion: 2,
			families: {
				example: {
					family: 'Example',
					display: 'swap',
					license: {
						id: 'test',
						file: 'licenses/test.txt',
						webEmbeddingAllowed: true,
						webEmbeddingBasis: 'test',
						transformationsAllowed: false,
					},
					faces: [
						{
							file: 'example-oblique.woff2',
							url: './example-oblique.woff2',
							format: 'woff2',
							style: 'oblique',
							obliqueAngle: 12,
							weight: 400,
						} as PreparedFontsManifest['families'][string]['faces'][number],
					],
				},
			},
		};
		expect(renderFontFaceCss(manifest)).toContain('font-style: oblique 12deg;');
	});

	it('refuses byte transformation without explicit license permission', async () => {
		await expect(
			prepareFonts(
				{
					output: { directory: './unused' },
					fonts: {
						example: {
							sources: ['./example.ttf'],
							strategy: 'woff2',
							license: {
								id: 'unknown',
								file: './license.txt',
								allowWebEmbedding: true,
								webEmbeddingBasis: 'Test fixture permission.',
							},
						},
					},
				},
				'/tmp'
			)
		).rejects.toThrow('license.allowTransformations is not true');
	});

	it('derives web-safe preparation strategy from each source extension', async () => {
		await expect(
			prepareFonts(
				{
					output: { directory: './unused' },
					fonts: {
						example: {
							sources: ['./example.ttf'],
							license: {
								id: 'test',
								file: './license.txt',
								allowWebEmbedding: true,
								webEmbeddingBasis: 'Test fixture permission.',
							},
						},
					},
				},
				'/tmp'
			)
		).rejects.toThrow('requests byte transformation');
	});

	it('rejects overlapping prepared face descriptors before CSS emission', () => {
		const base = {
			style: 'normal' as const,
			stretch: undefined,
		};
		expect(() =>
			assertNonOverlappingPreparedFaces(
				[
					{ ...base, weight: { min: 100, max: 800 } },
					{ ...base, weight: 400 },
				] as PreparedFontsManifest['families'][string]['faces'],
				'fonts.example'
			)
		).toThrow('overlapping normal faces');

		expect(() =>
			assertNonOverlappingPreparedFaces(
				[
					{ ...base, weight: { min: 100, max: 800 }, stretch: 100 },
					{ ...base, weight: 400, stretch: 125 },
				] as PreparedFontsManifest['families'][string]['faces'],
				'fonts.example'
			)
		).not.toThrow();
	});

	it('rejects unsafe family ids before writing files', async () => {
		await expect(
			prepareFonts(
				{
					output: { directory: './unused' },
					fonts: {
						'../example': {
							sources: ['./example.woff2'],
							strategy: 'copy',
							license: {
								id: 'unknown',
								file: './license.txt',
								allowWebEmbedding: true,
								webEmbeddingBasis: 'Test fixture permission.',
							},
						},
					},
				},
				'/tmp'
			)
		).rejects.toThrow('token- and filename-safe');
	});

	it('rejects duplicate configured CSS family ownership before inspecting files', async () => {
		await expect(
			prepareFonts(
				{
					output: { directory: './unused' },
					fonts: {
						first: {
							family: 'Example',
							sources: ['./first.woff2'],
							strategy: 'copy',
							license: {
								id: 'test',
								file: './license.txt',
								allowWebEmbedding: true,
								webEmbeddingBasis: 'test',
							},
						},
						second: {
							family: 'example',
							sources: ['./second.woff2'],
							strategy: 'copy',
							license: {
								id: 'test',
								file: './license.txt',
								allowWebEmbedding: true,
								webEmbeddingBasis: 'test',
							},
						},
					},
				},
				'/tmp'
			)
		).rejects.toThrow('use the same CSS family');
	});

	it('requires an explicit web-embedding permission basis', async () => {
		await expect(
			prepareFonts(
				{
					output: { directory: './unused' },
					fonts: {
						example: {
							sources: ['./example.woff2'],
							strategy: 'copy',
							license: {
								id: 'unknown',
								file: './license.txt',
								allowWebEmbedding: false,
								webEmbeddingBasis: 'Permission has not been confirmed.',
							},
						},
					},
				},
				'/tmp'
			)
		).rejects.toThrow('allowWebEmbedding must be true');
	});
});

describe('prepared output staged install', () => {
	it('removes stale managed files without touching unrelated output', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tfs-font-reconcile-'));
		const staging = path.join(root, 'staging');
		const destination = path.join(root, 'output');
		await fs.ensureDir(staging);
		await fs.ensureDir(destination);
		await fs.writeFile(path.join(staging, 'current.woff2'), 'current');
		await fs.ensureDir(path.join(destination, 'licenses'));
		await fs.writeFile(path.join(destination, 'stale.woff2'), 'stale');
		await fs.writeFile(path.join(destination, 'licenses', 'stale.txt'), 'stale license');
		await fs.writeFile(path.join(destination, 'unrelated.txt'), 'keep');

		await commitPreparedFiles(staging, destination, [
			'stale.woff2',
			path.join('licenses', 'stale.txt'),
		]);

		expect(await fs.pathExists(path.join(destination, 'stale.woff2'))).toBe(false);
		expect(await fs.pathExists(path.join(destination, 'licenses', 'stale.txt'))).toBe(false);
		expect(await fs.readFile(path.join(destination, 'current.woff2'), 'utf8')).toBe('current');
		expect(await fs.readFile(path.join(destination, 'unrelated.txt'), 'utf8')).toBe('keep');
		await fs.remove(root);
	});

	it('rolls back installed files when a later target cannot be committed', async () => {
		const root = await fs.mkdtemp(path.join(os.tmpdir(), 'tfs-font-transaction-'));
		const staging = path.join(root, 'staging');
		const destination = path.join(root, 'output');
		await fs.ensureDir(path.join(staging, 'z-blocked'));
		await fs.ensureDir(destination);
		await fs.writeFile(path.join(staging, 'a-first.css'), 'new');
		await fs.writeFile(path.join(staging, 'z-blocked', 'second.css'), 'new');
		await fs.writeFile(path.join(destination, 'a-first.css'), 'old');
		await fs.writeFile(path.join(destination, 'stale.woff2'), 'restore-me');
		await fs.writeFile(path.join(destination, 'z-blocked'), 'not-a-directory');

		await expect(commitPreparedFiles(staging, destination, ['stale.woff2'])).rejects.toThrow();
		expect(await fs.readFile(path.join(destination, 'a-first.css'), 'utf8')).toBe('old');
		expect(await fs.readFile(path.join(destination, 'stale.woff2'), 'utf8')).toBe('restore-me');
		expect(await fs.readFile(path.join(destination, 'z-blocked'), 'utf8')).toBe('not-a-directory');
		await fs.remove(root);
	});
});

describe('embedding guardrails', () => {
	const unrestricted = {
		noEmbedding: false,
		viewOnly: false,
		editable: false,
		noSubsetting: false,
		bitmapOnly: false,
	};

	it('refuses restrictive OS/2 embedding flags without a reasoned acknowledgement', () => {
		expect(() =>
			assertWebEmbeddingAllowed({ ...unrestricted, noEmbedding: true }, 'example')
		).toThrow('incompatible with normal web embedding');
		expect(() =>
			assertWebEmbeddingAllowed(
				{ ...unrestricted, viewOnly: true },
				'example',
				'Vendor confirmed the stale flag in writing.'
			)
		).not.toThrow();
	});
});
