import type { ResolvedSystem } from '../resolve/index.js';
import { tokensFor, type Token } from './tokens.js';

type Values = ReadonlyMap<string, string>;

const REFERENCE = /var\(--([a-z0-9-]+)\)/g;

function toMap(tokens: readonly Token[]): Values {
	return new Map(tokens.map((token) => [token.name, token.value]));
}

function block(selector: string, names: readonly string[], values: Values): string {
	if (names.length === 0) return '';
	return `${selector} {\n${names.map((name) => `\t--${name}: ${values.get(name)};`).join('\n')}\n}\n`;
}

function modeSelector(attribute: string, mode: string): string {
	return `[${attribute}="${mode}"]`;
}

/**
 * tokens.css: every token on :root, then one block per mode.
 *
 * A custom property that references another is evaluated where it is declared, so
 * when a mode changes a token, everything referring to it is re-declared in that
 * mode's block. Each block declares every token its axis controls, so selecting a
 * mode with no changes (e.g. `regular`) restores ordinary values inside another mode.
 *
 * A token whose own value follows one axis but whose references follow another (a
 * Shadow's shape follows Size while its colour follows Theme) also gets combined
 * selectors, so the other axis never resets its shape. They follow the nearest
 * ancestor's mode through one level of re-nesting on the same axis
 * (small → regular → light); deeper same-axis re-nesting is not supported.
 */
export function emitTokensCss(resolved: ResolvedSystem): string {
	const ordinaryTokens = tokensFor(resolved, resolved.ordinary);
	const names = ordinaryTokens.map((token) => token.name);
	const ordinary = toMap(ordinaryTokens);
	const modes = resolved.modes.map((mode) => ({
		...mode,
		tokens: toMap(tokensFor(resolved, mode.values)),
	}));
	const axes = [...new Set(modes.map((mode) => mode.axis))];

	// Which axis changes each token's own value.
	const ownAxis = new Map<string, string>();
	for (const mode of modes) {
		for (const name of names)
			if (mode.tokens.get(name) !== ordinary.get(name)) ownAxis.set(name, mode.axis);
	}

	// Tokens that refer, directly or through others, to any of `changed`.
	const referencedBy = new Map<string, string[]>();
	for (const [name, value] of ordinary) {
		for (const [, referenced] of value.matchAll(REFERENCE))
			referencedBy.set(referenced!, [...(referencedBy.get(referenced!) ?? []), name]);
	}
	const dependents = (changed: ReadonlySet<string>): Set<string> => {
		const found = new Set<string>();
		const queue = [...changed];
		while (queue.length > 0) {
			for (const dependent of referencedBy.get(queue.pop()!) ?? []) {
				if (!found.has(dependent) && !changed.has(dependent))
					(queue.push(dependent), found.add(dependent));
			}
		}
		return found;
	};

	let css = `/* Generated by Three Forma Styli. Do not edit. */\n${block(':root', names, ordinary)}`;
	let combined = '';
	for (const axis of axes) {
		const axisModes = modes.filter((mode) => mode.axis === axis);
		const own = new Set(names.filter((name) => ownAxis.get(name) === axis));
		const following = dependents(own);
		const declared = names.filter((name) => own.has(name) || following.has(name));
		for (const mode of axisModes) {
			const values = new Map(
				declared.map((name) => [name, (own.has(name) ? mode.tokens : ordinary).get(name)!])
			);
			css += block(modeSelector(mode.attribute, mode.mode), declared, values);
		}
		const inner = `[${axisModes[0]!.attribute}]`;
		for (const other of modes.filter((mode) => mode.axis !== axis)) {
			const both = names.filter((name) => following.has(name) && ownAxis.get(name) === other.axis);
			const outer = modeSelector(other.attribute, other.mode);
			const anyOuter = `[${other.attribute}]`;
			// Same element, or a descendant whose nearest `other` axis ancestor is this mode.
			const nested = `${outer} ${inner}:not(${anyOuter}):not(${outer} ${anyOuter}:not(${outer}) ${inner})`;
			combined += block(`${outer}${inner},\n${nested}`, both, other.tokens);
		}
	}
	return css + combined;
}
