import type { ResolvedSystem } from '../resolve/index.js';
import { TfsError } from '../resolve/issues.js';
import { cssVar } from './format.js';
import { rowName, rowsInOrder } from './names.js';

const HEADER = '/* Generated by Three Forma Styli. Do not edit. */\n';
const GLOBAL_PREFIX = 'text--';

type Rule = { readonly key: string; readonly declarations: readonly string[] };

type RoleShape = {
	readonly sizes: string[];
	readonly styles: string[];
	readonly weights: string[];
};

function roleShapes(resolved: ResolvedSystem): Record<string, RoleShape> {
	const roles = resolved.input.typography?.roles ?? {};
	return Object.fromEntries(
		Object.entries(roles).map(([name, role]) => [
			name,
			{
				sizes: rowsInOrder(role.sizes).map(([size]) => size),
				styles: [...(role.styles ?? ['normal'])],
				weights: typeof role.weights === 'number' ? [] : Object.keys(role.weights),
			},
		])
	);
}

/**
 * Size-row classes first, then style and weight classes, so an explicit choice
 * overrides the row's defaults at equal specificity.
 */
function rules(resolved: ResolvedSystem): Rule[] {
	const roles = resolved.input.typography?.roles ?? {};
	const sizeRules: Rule[] = [];
	const choiceRules: Rule[] = [];
	for (const [role, definition] of Object.entries(roles)) {
		const prefix = `text-${role}`;
		for (const [size] of rowsInOrder(definition.sizes)) {
			const row = `text-${rowName(role, size)}`;
			sizeRules.push({
				key: rowName(role, size),
				declarations: [
					`font-family: ${cssVar(`${prefix}-font-family`)}`,
					`font-size: ${cssVar(`${row}-font-size`)}`,
					`font-weight: ${cssVar(`${row}-font-weight`)}`,
					'font-style: normal',
					'font-synthesis: none',
					`line-height: ${cssVar(`${row}-line-height`)}`,
					`letter-spacing: ${cssVar(`${row}-letter-spacing`)}`,
					...(definition.textTransform
						? [`text-transform: ${cssVar(`${prefix}-text-transform`)}`]
						: []),
				],
			});
		}
		for (const style of definition.styles ?? ['normal']) {
			choiceRules.push({ key: `${role}-style-${style}`, declarations: [`font-style: ${style}`] });
		}
		if (typeof definition.weights !== 'number') {
			for (const weight of Object.keys(definition.weights)) {
				choiceRules.push({
					key: `${role}-weight-${weight}`,
					declarations: [`font-weight: ${cssVar(`${prefix}-font-weight-${weight}`)}`],
				});
			}
		}
	}
	const all = [...sizeRules, ...choiceRules];
	const seen = new Set<string>();
	const collisions = all.filter((rule) =>
		seen.has(rule.key) ? true : (seen.add(rule.key), false)
	);
	if (collisions.length > 0) {
		throw new TfsError(
			collisions.map((rule) => ({
				path: `.${GLOBAL_PREFIX}${rule.key}`,
				message: 'two roles produce this class name; rename one role',
			}))
		);
	}
	return all;
}

function css(resolved: ResolvedSystem, prefix: string): string {
	return (
		HEADER +
		rules(resolved)
			.map(
				(rule) =>
					`.${prefix}${rule.key} {\n${rule.declarations.map((d) => `\t${d};`).join('\n')}\n}\n`
			)
			.join('')
	);
}

/** typography.css: global classes such as `.text--label-s`. */
export function emitTypographyCss(resolved: ResolvedSystem): string {
	return css(resolved, GLOBAL_PREFIX);
}

/** typography.module.css: the same rules keyed for CSS Modules (`label-s`). */
export function emitTypographyModuleCss(resolved: ResolvedSystem): string {
	return css(resolved, '');
}

export function emitTypographyModuleTypes(resolved: ResolvedSystem): string {
	const keys = rules(resolved).map((rule) => `\treadonly ${JSON.stringify(rule.key)}: string;`);
	return `${HEADER}declare const classes: {\n${keys.join('\n')}\n};\nexport default classes;\n`;
}

/** typography.js: turns a typed selection into class names. */
export function emitTypographyJs(resolved: ResolvedSystem): string {
	return `${HEADER}const roles = ${JSON.stringify(roleShapes(resolved))};

/** Class names for a role, size, style and weight. Pass the CSS Modules object to get module names. */
export function typographyClassName(selection, classes) {
	const role = roles[selection.role];
	if (!role) throw new Error(\`Unknown typography role "\${selection.role}".\`);
	const size = selection.size ?? 'base';
	if (!role.sizes.includes(size)) throw new Error(\`Role "\${selection.role}" has no size "\${size}".\`);
	const keys = [size === 'base' ? selection.role : \`\${selection.role}-\${size}\`];
	if (selection.fontStyle !== undefined) {
		if (!role.styles.includes(selection.fontStyle)) throw new Error(\`Role "\${selection.role}" has no style "\${selection.fontStyle}".\`);
		keys.push(\`\${selection.role}-style-\${selection.fontStyle}\`);
	}
	if (selection.weight !== undefined) {
		if (!role.weights.includes(selection.weight)) throw new Error(\`Role "\${selection.role}" has no weight "\${selection.weight}".\`);
		keys.push(\`\${selection.role}-weight-\${selection.weight}\`);
	}
	return keys.map((key) => (classes ? classes[key] : \`${GLOBAL_PREFIX}\${key}\`)).join(' ');
}
`;
}

function union(values: readonly string[]): string {
	return values.length === 0 ? 'never' : values.map((value) => JSON.stringify(value)).join(' | ');
}

export function emitTypographyTypes(resolved: ResolvedSystem): string {
	const members = Object.entries(roleShapes(resolved)).map(
		([role, shape]) =>
			`\t| {\n\t\t\treadonly role: ${JSON.stringify(role)};\n\t\t\treadonly size?: ${union(shape.sizes)};\n\t\t\treadonly fontStyle?: ${union(shape.styles)};\n\t\t\treadonly weight?: ${union(shape.weights)};\n\t  }`
	);
	return `${HEADER}export type TypographySelection =\n${members.join('\n')};

export type TypographyRole = TypographySelection['role'];

/** Class names for a role, size, style and weight. Pass the CSS Modules object to get module names. */
export declare function typographyClassName(
	selection: TypographySelection,
	classes?: Readonly<Record<string, string>>
): string;
`;
}
