import { mkdtemp, readFile, rm, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { afterAll, describe, expect, it } from 'vitest';
import { buildProject, checkProject } from '../src/session/build.js';
import { loadConfig, type LoadedConfig } from '../src/session/config.js';
import { startDev } from '../src/session/dev.js';
import { project } from './everything.js';

const temporary: string[] = [];
afterAll(() => Promise.all(temporary.map((dir) => rm(dir, { recursive: true, force: true }))));

async function everythingInto(): Promise<LoadedConfig> {
	const loaded = await loadConfig(project);
	const outDir = join(await mkdtemp(join(tmpdir(), 'tfs-build-')), 'generated');
	temporary.push(outDir);
	return { ...loaded, outDir };
}

describe('loading tfs.config.ts', () => {
	it('runs the config and lists every file it imports', async () => {
		const loaded = await loadConfig(project);
		expect(Object.keys(loaded.config.system)).toContain('typography');
		expect(loaded.inputs.map((input) => input.split('/').pop())).toEqual(
			expect.arrayContaining([
				'tfs.config.ts',
				'axes.ts',
				'color.ts',
				'spacing.ts',
				'typography.ts',
			])
		);
	});
});

describe('tfs build and tfs check', () => {
	it('writes every output file, then reports it current', async () => {
		const loaded = await everythingInto();
		await buildProject(loaded);
		const styles = await readFile(join(loaded.outDir, 'styles.css'), 'utf8');
		expect(styles).toContain(
			'@import "./tokens.css";\n@import "./fonts.css";\n@import "./typography.css";'
		);
		expect(await checkProject(loaded)).toEqual([]);
	});

	it('check names each stale, missing or stray file', async () => {
		const loaded = await everythingInto();
		await buildProject(loaded);
		await writeFile(join(loaded.outDir, 'tokens.css'), 'edited');
		await rm(join(loaded.outDir, 'fonts.css'));
		await writeFile(join(loaded.outDir, 'notes.txt'), 'x');
		expect(await checkProject(loaded)).toEqual([
			'missing: fonts.css',
			'not generated by this config: notes.txt',
			'out of date: tokens.css',
		]);
	});

	it('an invalid system throws and leaves the previous output untouched', async () => {
		const loaded = await everythingInto();
		await buildProject(loaded);
		const before = await readFile(join(loaded.outDir, 'tokens.css'), 'utf8');
		const broken = structuredClone(loaded.config) as any;
		broken.system.spacing.step = 3;
		await expect(buildProject({ ...loaded, config: broken })).rejects.toThrow(
			'spacing.min: must be at least 0 and less than step 3 (got 4)'
		);
		expect(await readFile(join(loaded.outDir, 'tokens.css'), 'utf8')).toBe(before);
	});
});

describe('tfs dev', () => {
	it('rebuilds on save and keeps the last valid output through an invalid edit', async () => {
		// Inside the package, so `three-forma-styli` resolves as it would in a real project.
		const dir = await mkdtemp(join(project, '..', '.tmp-dev-'));
		temporary.push(dir);
		await mkdir(dir, { recursive: true });
		const spacing = (step: number) =>
			`import { defineSpacing } from 'three-forma-styli';\nexport const spacing = defineSpacing({ unit: 'px', min: 4, step: ${step}, count: 2 });\n`;
		await writeFile(join(dir, 'spacing.ts'), spacing(8));
		await writeFile(
			join(dir, 'tfs.config.ts'),
			`import { defineConfig } from 'three-forma-styli';\nimport { spacing } from './spacing.js';\nexport default defineConfig({ system: { axes: {}, spacing } });\n`
		);
		const lines: string[] = [];
		const session = await startDev(dir, (line) => lines.push(line), 5290);
		const css = () => readFile(join(dir, 'generated/tokens.css'), 'utf8');
		const until = async (condition: () => boolean) => {
			for (let i = 0; i < 100 && !condition(); i++) await new Promise((r) => setTimeout(r, 50));
			await session.settled();
		};
		try {
			expect(await css()).toContain('--sp-1: 8px;');

			const workbench = async () => (await fetch(`${session.url}/workbench.json`)).json();
			expect((await workbench()).problems).toEqual([]);
			expect(await (await fetch(`${session.url}/generated/tokens.css`)).text()).toContain(
				'--sp-1: 8px;'
			);

			await writeFile(join(dir, 'spacing.ts'), spacing(3));
			await until(() => lines.some((line) => line.startsWith('✗')));
			expect((await workbench()).problems).toEqual([
				'spacing.min: must be at least 0 and less than step 3 (got 4)',
			]);
			expect(lines.at(-1)).toContain(
				'spacing.min: must be at least 0 and less than step 3 (got 4)'
			);
			expect(lines.at(-1)).toContain('previous output kept');
			expect(await css()).toContain('--sp-1: 8px;');

			await writeFile(join(dir, 'spacing.ts'), spacing(10));
			await until(() => lines.filter((line) => line.startsWith('✓')).length >= 2);
			expect(await css()).toContain('--sp-1: 10px;');
		} finally {
			session.close();
		}
	});
});

describe('the tfs command', () => {
	it('prints help', () => {
		const result = spawnSync(
			process.execPath,
			[new URL('../dist/cli.js', import.meta.url).pathname, '--help'],
			{ encoding: 'utf8' }
		);
		expect(result.stdout).toContain('tfs build [dir]');
		expect(result.status).toBe(0);
	});
});

describe('the standard theme', () => {
	it('builds cleanly, fonts included', async () => {
		const loaded = await loadConfig(new URL('../themes/standard/', import.meta.url).pathname);
		const outDir = join(await mkdtemp(join(tmpdir(), 'tfs-standard-')), 'generated');
		temporary.push(outDir);
		const { resolved } = await buildProject({ ...loaded, outDir });
		expect(Object.keys(resolved.input.typography!.roles)).toEqual(['prose', 'heading', 'label']);
		expect(await readFile(join(outDir, 'fonts.css'), 'utf8')).toContain(
			'"JetBrains Mono fallback"'
		);
	});

	it('tfs init adds it to a new project, and refuses one that already has files', async () => {
		const { initProject } = await import('../src/session/init.js');
		const target = await mkdtemp(join(tmpdir(), 'tfs-init-'));
		temporary.push(target);
		await writeFile(join(target, 'package.json'), '{}');
		expect(await initProject(target)).toEqual([
			'axes.ts',
			'border.ts',
			'color.ts',
			'fonts',
			'motion.ts',
			'shadow.ts',
			'spacing.ts',
			'tfs.config.ts',
			'tsconfig.json',
			'typography.ts',
		]);
		await expect(initProject(target)).rejects.toThrow('already has files (axes.ts');
	});
});
