import { describe, it, expect } from 'vitest';
import { getHeaderLines, formatHeaderComment } from './header.js';
import type { FileHeaderInfo } from './header.js';

describe('getHeaderLines', () => {
	it('generates basic header lines with tool name and version', () => {
		const info: FileHeaderInfo = {
			toolName: 'three-forma-styli',
			toolVersion: '0.1.2',
		};

		const lines = getHeaderLines(info);

		expect(lines).toEqual([
			'Do not edit directly',
			'Generated by three-forma-styli v0.1.2',
		]);
	});

	it('includes timestamp when provided', () => {
		const info: FileHeaderInfo = {
			toolName: 'three-forma-styli',
			toolVersion: '1.0.0',
			timestamp: new Date('2025-12-11T18:00:00.000Z'),
		};

		const lines = getHeaderLines(info);

		expect(lines).toHaveLength(3);
		expect(lines[0]).toBe('Do not edit directly');
		expect(lines[1]).toBe('Generated by three-forma-styli v1.0.0');
		expect(lines[2]).toBe('Generated on 2025-12-11T18:00:00.000Z');
	});

	it('includes custom lines when provided', () => {
		const info: FileHeaderInfo = {
			toolName: 'tfs',
			toolVersion: '2.0.0',
			customLines: ['Custom line 1', 'Custom line 2'],
		};

		const lines = getHeaderLines(info);

		expect(lines).toEqual([
			'Do not edit directly',
			'Generated by tfs v2.0.0',
			'Custom line 1',
			'Custom line 2',
		]);
	});

	it('handles empty custom lines array', () => {
		const info: FileHeaderInfo = {
			toolName: 'tool',
			toolVersion: '1.0.0',
			customLines: [],
		};

		const lines = getHeaderLines(info);

		expect(lines).toHaveLength(2);
	});
});

describe('formatHeaderComment', () => {
	const testLines = ['Line 1', 'Line 2'];

	it('formats as block comment (default)', () => {
		const result = formatHeaderComment(testLines);

		expect(result).toBe(`/**
 * Line 1
 * Line 2
 */

`);
	});

	it('formats as block comment explicitly', () => {
		const result = formatHeaderComment(testLines, 'block');

		expect(result).toBe(`/**
 * Line 1
 * Line 2
 */

`);
	});

	it('formats as line comments', () => {
		const result = formatHeaderComment(testLines, 'line');

		expect(result).toBe(`// Line 1
// Line 2

`);
	});

	it('formats as XML comments', () => {
		const result = formatHeaderComment(testLines, 'xml');

		expect(result).toBe(`<!--
  Line 1
  Line 2
-->

`);
	});
});

describe('header integration', () => {
	it('produces expected CSS header output', () => {
		const info: FileHeaderInfo = {
			toolName: 'three-forma-styli',
			toolVersion: '0.1.3',
		};

		const lines = getHeaderLines(info);
		const header = formatHeaderComment(lines, 'block');

		expect(header).toBe(`/**
 * Do not edit directly
 * Generated by three-forma-styli v0.1.3
 */

`);
	});
});
