/**
 * File Header Generation
 *
 * Format-agnostic header content for generated files.
 * Each transformer wraps this content in format-appropriate comment syntax.
 */

/**
 * Metadata for generated file headers
 */
export interface FileHeaderInfo {
	/** Tool name (e.g., "three-forma-styli") */
	toolName: string;

	/** Tool version (e.g., "0.1.2") */
	toolVersion: string;

	/** Optional timestamp. Off by default to avoid noisy git diffs in CI/CD. */
	timestamp?: Date;

	/** Optional additional lines to include in header */
	customLines?: string[];
}

/**
 * Generate header content lines (format-agnostic)
 *
 * @example
 * ```ts
 * const lines = getHeaderLines({
 *   toolName: 'three-forma-styli',
 *   toolVersion: '0.1.2'
 * });
 * // ['Do not edit directly', 'Generated by three-forma-styli v0.1.2']
 * ```
 */
export function getHeaderLines(info: FileHeaderInfo): string[] {
	const lines = [
		'Do not edit directly',
		`Generated by ${info.toolName} v${info.toolVersion}`,
	];

	if (info.timestamp) {
		lines.push(`Generated on ${info.timestamp.toISOString()}`);
	}

	if (info.customLines && info.customLines.length > 0) {
		lines.push(...info.customLines);
	}

	return lines;
}

/**
 * Comment style definitions for different output formats
 */
export type CommentStyle = 'block' | 'line' | 'xml';

/**
 * Format header lines as a comment block
 *
 * @param lines - Header content lines
 * @param style - Comment style for the target format
 * @returns Formatted comment string with trailing newlines
 */
export function formatHeaderComment(
	lines: string[],
	style: CommentStyle = 'block'
): string {
	switch (style) {
		case 'block':
			// /* */ style (CSS, JS, TS)
			return `/**\n${lines.map((l) => ` * ${l}`).join('\n')}\n */\n\n`;

		case 'line':
			// // style (single-line comments)
			return `${lines.map((l) => `// ${l}`).join('\n')}\n\n`;

		case 'xml':
			// <!-- --> style (HTML, XML)
			return `<!--\n${lines.map((l) => `  ${l}`).join('\n')}\n-->\n\n`;
	}
}
