import type { GeneratorConfig, IR, PartialDesignSystem } from '@three-forma-styli/core';
import {
	resolveIdentityGroups,
	typographyClassResolverDeclaration,
	typographyClassResolverJavascript,
	typographyContractData,
	typographyContractTypes,
} from '@three-forma-styli/core';
import { projectSystemContract } from '../system-typescript.js';
import type { ProjectRuntimeColorThemes } from '../project.js';

type JsonPrimitive = string | number | boolean | null;
type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

function assertJsonValue(value: unknown, location = 'contract'): asserts value is JsonValue {
	if (value === null || typeof value === 'string' || typeof value === 'boolean') return;
	if (typeof value === 'number') {
		if (!Number.isFinite(value)) throw new Error(`${location} contains a non-finite number.`);
		return;
	}
	if (Array.isArray(value)) {
		value.forEach((entry, index) => assertJsonValue(entry, `${location}[${index}]`));
		return;
	}
	if (typeof value === 'object') {
		for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
			if (entry === undefined) throw new Error(`${location}.${key} contains undefined.`);
			assertJsonValue(entry, `${location}.${key}`);
		}
		return;
	}
	throw new Error(`${location} is not JSON-safe.`);
}

function propertyName(name: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function literalType(
	value: JsonValue,
	depth = 0,
	path: Array<string | number> = [],
	widenNumber?: (path: Array<string | number>) => boolean
): string {
	const indent = '\t'.repeat(depth);
	const child = '\t'.repeat(depth + 1);
	if (value === null) return 'null';
	if (typeof value === 'number' && widenNumber?.(path)) return 'number';
	if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
		return JSON.stringify(value);
	}
	if (Array.isArray(value)) {
		if (value.length === 0) return 'readonly []';
		return `readonly [\n${value
			.map(
				(entry, index) => `${child}${literalType(entry, depth + 1, [...path, index], widenNumber)}`
			)
			.join(',\n')}\n${indent}]`;
	}
	const entries = Object.entries(value);
	if (entries.length === 0) return '{}';
	return `{\n${entries
		.map(
			([key, entry]) =>
				`${child}readonly ${propertyName(key)}: ${literalType(entry, depth + 1, [...path, key], widenNumber)};`
		)
		.join('\n')}\n${indent}}`;
}

/** Dependency-free ESM plus a declaration that preserves every authored literal. */
export function renderLiteralModule(
	exportName: string,
	value: unknown,
	typeLines: string[] = [],
	options: { widenNumber?: (path: Array<string | number>) => boolean } = {}
): { javascript: string; declaration: string } {
	assertJsonValue(value);
	const header = '/** Generated by Three Forma Styli. Do not edit by hand. */';
	return {
		javascript: `${header}\nexport const ${exportName} = ${JSON.stringify(value, null, 2)};\n`,
		declaration: [
			header,
			`export declare const ${exportName}: ${literalType(value, 0, [], options.widenNumber)};`,
			...typeLines,
			'',
		].join('\n'),
	};
}

export function renderSystemContract(system: PartialDesignSystem, ir: IR) {
	const legacy = projectSystemContract(system, ir);
	const contract = {
		...legacy,
		modes: Object.fromEntries(
			Object.entries(legacy.modes).map(([category, mode]) => [
				category,
				mode.default === '' ? { default: null, entries: {} } : mode,
			])
		),
		scales: {
			...legacy.scales,
			time: legacy.scales.time.default === '' ? { default: null, entries: {} } : legacy.scales.time,
		},
	};
	return renderLiteralModule('tfsSystem', contract, [
		'export type TfsSystem = typeof tfsSystem;',
		'export type TfsColorMode = keyof typeof tfsSystem.modes.color.entries;',
		'export type TfsSizeMode = keyof typeof tfsSystem.modes.size.entries;',
		'export type TfsTimeScale = keyof typeof tfsSystem.scales.time.entries;',
	]);
}

export function renderTypographyContract(ir: IR) {
	if (!ir.typography || Object.keys(ir.typography.roles).length === 0) {
		throw new Error('A typography system with semantic roles is required.');
	}
	const rendered = renderLiteralModule('typography', typographyContractData(ir.typography), [
		typographyContractTypes(ir.typography).trimEnd(),
		typographyClassResolverDeclaration(),
	]);
	return {
		javascript: `${rendered.javascript}\n${typographyClassResolverJavascript()}`,
		declaration: rendered.declaration,
	};
}

function defaultMode<T extends { isDefault?: boolean }>(entries: readonly T[]): T | undefined {
	return entries.find((entry) => entry.isDefault) ?? entries[0];
}

function numericScaleIdentities(range: number): string[] {
	return ['min', ...Array.from({ length: range }, (_, index) => String(index + 1))];
}

function tokenCatalogueData(system: PartialDesignSystem, ir: IR, generator: GeneratorConfig) {
	const colorMode = defaultMode(system.colors?.modes ?? []);
	const spacingMode = defaultMode(system.spacing?.modes ?? []);
	const typographyMode = defaultMode(system.typography?.modes ?? []);
	const colorIdentities = Object.keys(colorMode?.tokens ?? {});
	const alphaIdentities = system.alpha
		? ['non', ...ir.alpha!.positions]
		: Object.keys(selectedAlphaSchedule(system) ?? {});
	const tokenIdentities = [
		...new Set(
			[...Object.values(ir.tokens), ...Object.values(ir.overrideTokens).flatMap(Object.values)].map(
				(token) => token.name
			)
		),
	].sort();

	return {
		schemaVersion: 1,
		prefixes: {
			color: generator.prefixes.color,
			alphaModifier: generator.colorFormat.alphaModifier,
		},
		colorIdentities,
		alphaIdentities,
		colorGroups: resolveIdentityGroups(colorIdentities, system.colors?.groups),
		alphaScaleIdentities: Object.keys(system.alpha?.scales ?? {}),
		spacingIdentities: spacingMode ? numericScaleIdentities(spacingMode.tokens.range) : [],
		gapIdentities: system.gap ? ['min', 's', 'l', 'max'] : [],
		fontSizeIdentities: typographyMode ? numericScaleIdentities(typographyMode.tokens.range) : [],
		borderRadiusIdentities: system.border?.radius ? ['min', 's', 'l', 'max'] : [],
		timeScaleIdentities: (system.time?.scales ?? []).map((scale) => scale.name),
		motionCompositeIdentities: Object.keys(system.motion?.composites ?? {}),
		boxShadowCompositeIdentities: Object.keys(system.shadows?.box ?? {}),
		textShadowCompositeIdentities: Object.keys(system.shadows?.text ?? {}),
		tokenIdentities,
	} as const;
}

/** Compact, dependency-free public catalogue. Detailed resolved state stays in evidence. */
export function renderTokensContract(
	system: PartialDesignSystem,
	ir: IR,
	generator: GeneratorConfig
) {
	const data = tokenCatalogueData(system, ir, generator);
	const header = '/** Generated by Three Forma Styli. Do not edit by hand. */';
	const declarations = renderLiteralModule('tokenCatalogue', data)
		.declaration.split('\n')
		.slice(1, -1)
		.join('\n');
	const javascript = `${header}
export const tokenCatalogue = ${JSON.stringify(data, null, 2)};
export const colorIdentities = tokenCatalogue.colorIdentities;
export const alphaIdentities = tokenCatalogue.alphaIdentities;
export const alphaScaleIdentities = tokenCatalogue.alphaScaleIdentities;
export const colorGroups = tokenCatalogue.colorGroups;
export const borderRadiusIdentities = tokenCatalogue.borderRadiusIdentities;
export const gapIdentities = tokenCatalogue.gapIdentities;
export const spacingIdentities = tokenCatalogue.spacingIdentities;
export const fontSizeIdentities = tokenCatalogue.fontSizeIdentities;
export const timeScaleIdentities = tokenCatalogue.timeScaleIdentities;
export const motionCompositeIdentities = tokenCatalogue.motionCompositeIdentities;
export const boxShadowCompositeIdentities = tokenCatalogue.boxShadowCompositeIdentities;
export const textShadowCompositeIdentities = tokenCatalogue.textShadowCompositeIdentities;
export const tokenIdentities = tokenCatalogue.tokenIdentities;

export function colorVariable(color, alpha) {
  if (!colorIdentities.includes(color)) throw new Error(\`Unknown color identity "\${color}".\`);
  if (alpha !== undefined && !alphaIdentities.includes(alpha)) throw new Error(\`Unknown alpha identity "\${alpha}".\`);
  const suffix = alpha === undefined ? "" : \`-\${tokenCatalogue.prefixes.alphaModifier}-\${alpha}\`;
  return \`--\${tokenCatalogue.prefixes.color}-\${color}\${suffix}\`;
}

export function colorReference(color, alpha) {
  return \`var(\${colorVariable(color, alpha)})\`;
}

export function tokenVariable(token) {
  if (!tokenIdentities.includes(token)) throw new Error(\`Unknown token identity "\${token}".\`);
  return \`--\${token}\`;
}

export function tokenReference(token) {
  return \`var(\${tokenVariable(token)})\`;
}

export function colorRampStyle(color, localVariable) {
  if (!/^--[a-z_][a-z0-9_-]*$/i.test(localVariable)) throw new Error("Local variable must be a CSS custom property name beginning with --.");
  return Object.fromEntries([
    [localVariable, colorReference(color)],
    ...alphaIdentities.map((alpha) => [\`\${localVariable}-\${tokenCatalogue.prefixes.alphaModifier}-\${alpha}\`, colorReference(color, alpha)]),
  ]);
}
`;
	const declaration = `${header}
${declarations}
export declare const colorIdentities: typeof tokenCatalogue.colorIdentities;
export declare const alphaIdentities: typeof tokenCatalogue.alphaIdentities;
export declare const alphaScaleIdentities: typeof tokenCatalogue.alphaScaleIdentities;
export declare const colorGroups: typeof tokenCatalogue.colorGroups;
export declare const borderRadiusIdentities: typeof tokenCatalogue.borderRadiusIdentities;
export declare const gapIdentities: typeof tokenCatalogue.gapIdentities;
export declare const spacingIdentities: typeof tokenCatalogue.spacingIdentities;
export declare const fontSizeIdentities: typeof tokenCatalogue.fontSizeIdentities;
export declare const timeScaleIdentities: typeof tokenCatalogue.timeScaleIdentities;
export declare const motionCompositeIdentities: typeof tokenCatalogue.motionCompositeIdentities;
export declare const boxShadowCompositeIdentities: typeof tokenCatalogue.boxShadowCompositeIdentities;
export declare const textShadowCompositeIdentities: typeof tokenCatalogue.textShadowCompositeIdentities;
export declare const tokenIdentities: typeof tokenCatalogue.tokenIdentities;
export type ColorIdentity = typeof colorIdentities[number];
export type AlphaIdentity = typeof alphaIdentities[number];
export type AlphaScaleIdentity = typeof alphaScaleIdentities[number];
export type ColorGroupIdentity = keyof typeof colorGroups;
export type ColorIdentityIn<Group extends ColorGroupIdentity> = typeof colorGroups[Group][number];
export type BorderRadiusIdentity = typeof borderRadiusIdentities[number];
export type GapIdentity = typeof gapIdentities[number];
export type SpacingIdentity = typeof spacingIdentities[number];
export type FontSizeIdentity = typeof fontSizeIdentities[number];
export type TimeScaleIdentity = typeof timeScaleIdentities[number];
export type MotionCompositeIdentity = typeof motionCompositeIdentities[number];
export type BoxShadowCompositeIdentity = typeof boxShadowCompositeIdentities[number];
export type TextShadowCompositeIdentity = typeof textShadowCompositeIdentities[number];
export type TokenIdentity = typeof tokenIdentities[number];
export type ColorVariable<Color extends ColorIdentity, Alpha extends AlphaIdentity | undefined = undefined> = Alpha extends AlphaIdentity ? \`--${data.prefixes.color}-\${Color}-${data.prefixes.alphaModifier}-\${Alpha}\` : \`--${data.prefixes.color}-\${Color}\`;
export declare function colorVariable<Color extends ColorIdentity, Alpha extends AlphaIdentity | undefined = undefined>(color: Color, alpha?: Alpha): ColorVariable<Color, Alpha>;
export declare function colorReference<Color extends ColorIdentity, Alpha extends AlphaIdentity | undefined = undefined>(color: Color, alpha?: Alpha): \`var(\${ColorVariable<Color, Alpha>})\`;
export declare function tokenVariable<Token extends TokenIdentity>(token: Token): \`--\${Token}\`;
export declare function tokenReference<Token extends TokenIdentity>(token: Token): \`var(--\${Token})\`;
export type ColorRampStyle<Prefix extends \`--\${string}\`> = { [Key in Prefix | \`\${Prefix}-${data.prefixes.alphaModifier}-\${AlphaIdentity}\`]: string };
export declare function colorRampStyle<Color extends ColorIdentity, Prefix extends \`--\${string}\`>(color: Color, localVariable: Prefix): ColorRampStyle<Prefix>;
`;
	return { javascript, declaration };
}

function normalizedColor(color: unknown): { l: number; c: number; h: number } {
	if (!color || typeof color !== 'object') throw new Error('Color tokens must be OKLCH objects.');
	const candidate = color as { l?: unknown; c?: unknown; h?: unknown };
	if (typeof candidate.l !== 'number' || !Number.isFinite(candidate.l)) {
		throw new Error('Color component l must be a finite number.');
	}
	for (const component of ['c', 'h'] as const) {
		if (
			candidate[component] !== undefined &&
			(typeof candidate[component] !== 'number' || !Number.isFinite(candidate[component]))
		) {
			throw new Error(`Color component ${component} must be a finite number when provided.`);
		}
	}
	return {
		l: candidate.l,
		c: (candidate.c as number | undefined) ?? 0,
		h: (candidate.h as number | undefined) ?? 0,
	};
}

function selectedAlphaSchedule(
	system: PartialDesignSystem
): Readonly<Record<string, number>> | undefined {
	if (!system.alpha) return undefined;
	const scaleName = system.colors?.alphaScale ?? system.alpha.defaultScale;
	const scale = system.alpha.scales[scaleName];
	if (!scale) throw new Error(`Unknown alpha scale "${scaleName}".`);
	return { non: 0, ...scale.values };
}

/** Compact author-facing mode data: complete default palette, named authored patches. */
export function nativeColorModesContract(system: PartialDesignSystem) {
	if (!system.colors) throw new Error('A color system is required for native color modes.');
	const defaultMode = system.colors.modes.find((mode) => mode.isDefault) ?? system.colors.modes[0];
	if (!defaultMode) throw new Error('Native color modes require one default color mode.');
	const ordered = [defaultMode, ...system.colors.modes.filter((mode) => mode !== defaultMode)];
	const colorIdentities = [...new Set(ordered.flatMap((mode) => Object.keys(mode.tokens)))];
	return {
		schemaVersion: 2,
		defaultMode: defaultMode.name,
		colorIdentities,
		alphaSchedule: selectedAlphaSchedule(system) ?? null,
		modes: ordered.map((mode) => ({
			name: mode.name,
			isDefault: mode === defaultMode,
			metadata: mode.metadata ?? null,
			source: {
				colors: Object.fromEntries(
					Object.entries(mode.tokens).map(([name, color]) => [name, normalizedColor(color)])
				),
			},
		})),
	} as const;
}

export function renderNativeColorModesContract(system: PartialDesignSystem) {
	return renderLiteralModule(
		'nativeColorModes',
		nativeColorModesContract(system),
		['export type NativeColorMode = typeof nativeColorModes.modes[number]["name"];'],
		{
			widenNumber: (path) => {
				const keys = path.filter((part): part is string => typeof part === 'string');
				const last = keys.at(-1);
				return (
					(keys.includes('alphaSchedule') && last !== 'non') ||
					(keys.includes('colors') && ['l', 'c', 'h'].includes(last ?? ''))
				);
			},
		}
	);
}

/** Strict runtime-theme policy derived from the same authored color system and generator config. */
function runtimeColorIdentities(
	system: PartialDesignSystem,
	policy: ProjectRuntimeColorThemes | undefined
): string[] {
	if (!system.colors) return [];
	if (!policy) return [];
	const colorMode = defaultMode(system.colors.modes);
	const identities = Object.keys(colorMode?.tokens ?? {});
	const groups = resolveIdentityGroups(identities, system.colors.groups);
	const selected = policy.colors.include.flatMap((selection) => {
		if (typeof selection === 'string') return [selection];
		const members = groups[selection.group];
		if (!members)
			throw new Error(`Runtime color themes reference unknown group "${selection.group}".`);
		return members;
	});
	const unique = [...new Set(selected)];
	for (const identity of unique) {
		if (!identities.includes(identity)) {
			throw new Error(`Runtime color themes reference unknown color identity "${identity}".`);
		}
	}
	if (unique.length === 0)
		throw new Error('Runtime color themes must include at least one color identity.');
	return unique;
}

export function runtimeColorThemeContract(
	system: PartialDesignSystem,
	generator: GeneratorConfig,
	policy?: ProjectRuntimeColorThemes
) {
	if (!system.colors?.luminance || !policy) {
		throw new Error(
			'colors.luminance and project.runtime.colorThemes are required for runtime color themes.'
		);
	}
	const defaultMode = system.colors.modes.find((mode) => mode.isDefault) ?? system.colors.modes[0];
	if (!defaultMode) throw new Error('Runtime color themes require one default color mode.');
	const enforce = policy.enforce ?? [];
	if (new Set(enforce).size !== enforce.length || enforce.some((name) => name !== 'luminance')) {
		throw new Error('Runtime color theme enforcement must contain only one "luminance" entry.');
	}
	const alphaSchedule = selectedAlphaSchedule(system);
	return {
		schemaVersion: 2,
		colorIdentities: runtimeColorIdentities(system, policy),
		enforce,
		...(alphaSchedule ? { alphaSchedule } : {}),
		luminance: system.colors.luminance,
		prefixes: { color: generator.prefixes.color },
		colorFormat: { alphaModifier: generator.colorFormat.alphaModifier },
	} as const;
}

export function renderRuntimeColorThemeContract(
	system: PartialDesignSystem,
	generator: GeneratorConfig,
	policy?: ProjectRuntimeColorThemes
) {
	return renderLiteralModule(
		'runtimeColorThemeConfig',
		runtimeColorThemeContract(system, generator, policy),
		[
			'export type RuntimeColorIdentity = typeof runtimeColorThemeConfig.colorIdentities[number];',
			'export type RuntimeColorThemeInput = {',
			'  readonly polarity: "negative" | "positive";',
			'  readonly colors: Readonly<Record<RuntimeColorIdentity, { readonly l: number; readonly c: number; readonly h: number }>>;',
			'};',
		],
		{
			widenNumber: (path) => {
				const keys = path.filter((part): part is string => typeof part === 'string');
				return (
					(keys.includes('alphaSchedule') && keys.at(-1) !== 'non') ||
					keys.at(-1) === 'minimumLuminanceDelta'
				);
			},
		}
	);
}
