import type { IR, PartialDesignSystem } from '@three-forma-styli/core';
import { typographyContractData, typographyContractTypes } from '@three-forma-styli/core';
import { projectSystemContract } from '../system-typescript.js';

type JsonPrimitive = string | number | boolean | null;
type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

function assertJsonValue(value: unknown, location = 'contract'): asserts value is JsonValue {
	if (value === null || typeof value === 'string' || typeof value === 'boolean') return;
	if (typeof value === 'number') {
		if (!Number.isFinite(value)) throw new Error(`${location} contains a non-finite number.`);
		return;
	}
	if (Array.isArray(value)) {
		value.forEach((entry, index) => assertJsonValue(entry, `${location}[${index}]`));
		return;
	}
	if (typeof value === 'object') {
		for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
			if (entry === undefined) throw new Error(`${location}.${key} contains undefined.`);
			assertJsonValue(entry, `${location}.${key}`);
		}
		return;
	}
	throw new Error(`${location} is not JSON-safe.`);
}

function propertyName(name: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function literalType(
	value: JsonValue,
	depth = 0,
	path: Array<string | number> = [],
	widenNumber?: (path: Array<string | number>) => boolean
): string {
	const indent = '\t'.repeat(depth);
	const child = '\t'.repeat(depth + 1);
	if (value === null) return 'null';
	if (typeof value === 'number' && widenNumber?.(path)) return 'number';
	if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
		return JSON.stringify(value);
	}
	if (Array.isArray(value)) {
		if (value.length === 0) return 'readonly []';
		return `readonly [\n${value
			.map(
				(entry, index) => `${child}${literalType(entry, depth + 1, [...path, index], widenNumber)}`
			)
			.join(',\n')}\n${indent}]`;
	}
	const entries = Object.entries(value);
	if (entries.length === 0) return '{}';
	return `{\n${entries
		.map(
			([key, entry]) =>
				`${child}readonly ${propertyName(key)}: ${literalType(entry, depth + 1, [...path, key], widenNumber)};`
		)
		.join('\n')}\n${indent}}`;
}

/** Dependency-free ESM plus a declaration that preserves every authored literal. */
export function renderLiteralModule(
	exportName: string,
	value: unknown,
	typeLines: string[] = [],
	options: { widenNumber?: (path: Array<string | number>) => boolean } = {}
): { javascript: string; declaration: string } {
	assertJsonValue(value);
	const header = '/** Generated by Three Forma Styli. Do not edit by hand. */';
	return {
		javascript: `${header}\nexport const ${exportName} = ${JSON.stringify(value, null, 2)};\n`,
		declaration: [
			header,
			`export declare const ${exportName}: ${literalType(value, 0, [], options.widenNumber)};`,
			...typeLines,
			'',
		].join('\n'),
	};
}

export function renderSystemContract(system: PartialDesignSystem, ir: IR) {
	const legacy = projectSystemContract(system, ir);
	const contract = {
		...legacy,
		modes: Object.fromEntries(
			Object.entries(legacy.modes).map(([category, mode]) => [
				category,
				mode.default === '' ? { default: null, entries: {} } : mode,
			])
		),
	};
	return renderLiteralModule('tfsSystem', contract, [
		'export type TfsSystem = typeof tfsSystem;',
		'export type TfsColorMode = keyof typeof tfsSystem.modes.color.entries;',
		'export type TfsSizeMode = keyof typeof tfsSystem.modes.size.entries;',
		'export type TfsTimeMode = keyof typeof tfsSystem.modes.time.entries;',
	]);
}

export function renderTypographyContract(ir: IR) {
	if (!ir.typography || Object.keys(ir.typography.roles).length === 0) {
		throw new Error('A typography system with semantic roles is required.');
	}
	return renderLiteralModule('typography', typographyContractData(ir.typography), [
		typographyContractTypes(ir.typography).trimEnd(),
	]);
}

function normalizedColor(color: unknown): { l: number; c: number; h: number } {
	if (!color || typeof color !== 'object') throw new Error('Color tokens must be OKLCH objects.');
	const candidate = color as { l?: unknown; c?: unknown; h?: unknown };
	if (typeof candidate.l !== 'number' || !Number.isFinite(candidate.l)) {
		throw new Error('Color component l must be a finite number.');
	}
	for (const component of ['c', 'h'] as const) {
		if (
			candidate[component] !== undefined &&
			(typeof candidate[component] !== 'number' || !Number.isFinite(candidate[component]))
		) {
			throw new Error(`Color component ${component} must be a finite number when provided.`);
		}
	}
	return {
		l: candidate.l,
		c: (candidate.c as number | undefined) ?? 0,
		h: (candidate.h as number | undefined) ?? 0,
	};
}

/** Compact author-facing mode data: complete default palette, named authored patches. */
export function nativeColorModesContract(system: PartialDesignSystem) {
	if (!system.colors) throw new Error('A color system is required for native color modes.');
	const defaultMode = system.colors.modes.find((mode) => mode.isDefault) ?? system.colors.modes[0];
	if (!defaultMode) throw new Error('Native color modes require one default color mode.');
	const ordered = [defaultMode, ...system.colors.modes.filter((mode) => mode !== defaultMode)];
	const colorNames = [...new Set(ordered.flatMap((mode) => Object.keys(mode.tokens)))];
	return {
		schemaVersion: 1,
		defaultMode: defaultMode.name,
		colorNames,
		alphaSchedule: defaultMode.alphaSchedule ?? system.colors.alphaSchedule ?? null,
		modes: ordered.map((mode) => ({
			name: mode.name,
			isDefault: mode === defaultMode,
			metadata: mode.metadata ?? null,
			source: {
				colors: Object.fromEntries(
					Object.entries(mode.tokens).map(([name, color]) => [name, normalizedColor(color)])
				),
				alphaSchedule: mode.alphaSchedule ?? null,
			},
		})),
	} as const;
}

export function renderNativeColorModesContract(system: PartialDesignSystem) {
	return renderLiteralModule(
		'nativeColorModes',
		nativeColorModesContract(system),
		['export type NativeColorMode = typeof nativeColorModes.modes[number]["name"];'],
		{
			widenNumber: (path) => {
				const keys = path.filter((part): part is string => typeof part === 'string');
				const last = keys.at(-1);
				return (
					keys.includes('alphaSchedule') ||
					(keys.includes('colors') && ['l', 'c', 'h'].includes(last ?? ''))
				);
			},
		}
	);
}
