import { describe, expect, it } from 'vitest';
import { generate } from '../generator/index.js';
import type { PartialDesignSystem } from '../types.js';
import { toFigmaJson } from './figma-json.js';

const colors: PartialDesignSystem = {
	colors: {
		modes: [
			{
				name: 'light',
				isDefault: true,
				tokens: {
					ink: { mode: 'oklch', l: 0, c: 0, h: 0 },
				},
			},
			{
				name: 'dark',
				tokens: {
					ink: { mode: 'oklch', l: 1, c: 0, h: 0 },
				},
			},
		],
		alphaSchedule: { half: 0.5 },
	},
};

function generateHexIr() {
	return generate(colors, {
		colorFormat: { base: 'hex', alpha: 'hexa', alphaModifier: 'a' },
	});
}

describe('toFigmaJson', () => {
	it('emits valid DTCG 2025.10 color values and schema metadata', () => {
		const output = JSON.parse(
			toFigmaJson(generateHexIr(), {
				collectionName: 'Brand',
				fileHeader: { toolName: 'tfs', toolVersion: '1.2.3' },
			})
		);

		expect(output.$schema).toBe('https://www.designtokens.org/schemas/2025.10/format.json');
		expect(output.$extensions['com.three-forma-styli'].generator).toContain(
			'Generated by tfs v1.2.3'
		);
		expect(output.color.$type).toBe('color');
		expect(output.color['clr-ink'].$value).toEqual({
			colorSpace: 'srgb',
			components: [0, 0, 0],
			hex: '#000000',
		});
		expect(output.color['clr-ink-a-half'].$value).toEqual({
			colorSpace: 'srgb',
			components: [0, 0, 0],
			alpha: 0.501961,
			hex: '#000000',
		});
	});

	it('preserves color modes in a namespaced DTCG extension', () => {
		const output = JSON.parse(toFigmaJson(generateHexIr(), { collectionName: 'Brand' }));
		const extension = output.color['clr-ink'].$extensions['com.three-forma-styli'];

		expect(extension.collection).toBe('Brand');
		expect(extension.modes.light.hex).toBe('#000000');
		expect(extension.modes.dark.hex).toBe('#ffffff');
	});

	it('emits layered box/text recipes as DTCG shadow composites', () => {
		const system: PartialDesignSystem = {
			...colors,
			shadows: {
				unit: 'px',
				box: {
					elevation: {
						base: [
							{ x: 0, y: 1, blur: 3, color: { color: 'ink', alpha: 'half' } },
							{
								x: 0,
								y: 8,
								blur: 24,
								spread: -4,
								color: { color: 'ink', alpha: 'half' },
							},
						],
					},
				},
				text: {
					glow: {
						base: [{ x: 0, y: 0, blur: 8, color: { color: 'ink', alpha: 'half' } }],
					},
				},
			},
		};
		const ir = generate(system, {
			colorFormat: { base: 'hex', alpha: 'hexa', alphaModifier: 'a' },
		});
		const output = JSON.parse(toFigmaJson(ir));

		expect(output.shadow.$type).toBe('shadow');
		expect(output.shadow['box-elevation'].$value).toHaveLength(2);
		expect(output.shadow['box-elevation'].$value[1]).toEqual({
			color: '{color.clr-ink-a-half}',
			offsetX: { value: 0, unit: 'px' },
			offsetY: { value: 8, unit: 'px' },
			blur: { value: 24, unit: 'px' },
			spread: { value: -4, unit: 'px' },
		});
		expect(output.shadow['text-glow'].$value.spread).toEqual({
			value: 0,
			unit: 'px',
		});
		expect(output.shadow['text-glow'].$extensions['com.three-forma-styli'].kind).toBe('text');
	});

	it('emits Figma REST API color values for every mode', () => {
		const output = JSON.parse(
			toFigmaJson(
				generateHexIr(),
				{
					collectionName: 'Brand',
				},
				'figma-variables'
			)
		);
		const collection = output.collections[0];
		const ink = collection.variables.find(
			(variable: { name: string }) => variable.name === 'clr-ink'
		);

		expect(collection).toMatchObject({
			name: 'Brand',
			defaultMode: 'light',
			modes: ['light', 'dark'],
		});
		expect(ink.values.light).toEqual({
			hex: '#000000',
			rgba: { r: 0, g: 0, b: 0, a: 1 },
		});
		expect(ink.values.dark.rgba).toEqual({ r: 1, g: 1, b: 1, a: 1 });
	});

	it('labels Display-P3 components correctly without misusing CSS hex fallback', () => {
		const p3Ir = generate(colors, {
			colorFormat: { base: 'hex-p3', alpha: 'hexa-p3', alphaModifier: 'a' },
		});
		const output = JSON.parse(toFigmaJson(p3Ir, { colorSpace: 'display-p3' }));
		const value = output.color['clr-ink'].$value;

		expect(value.colorSpace).toBe('display-p3');
		expect(value.components).toHaveLength(3);
		expect(value).not.toHaveProperty('hex');
	});

	it('fails loudly when the IR is not generated in a compatible hex format', () => {
		expect(() => toFigmaJson(generate(colors))).toThrow(
			'Figma JSON requires 6- or 8-digit hex colors'
		);
	});

	it('fails loudly when the IR contains no color family', () => {
		const spacingOnly = generate({
			spacing: {
				modes: [
					{
						name: 'default',
						isDefault: true,
						tokens: { unit: 'px', base: 8, min: 4, range: 2 },
					},
				],
			},
		});

		expect(() => toFigmaJson(spacingOnly)).toThrow('Design JSON requires a color token family');
	});
});
