import { readFileSync } from 'node:fs';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { describe, expect, it } from 'vitest';
import { generate } from '../generator/index.js';
import type { PartialDesignSystem } from '../types.js';
import { toFigmaJson } from './figma-json.js';

const dtcgSchema = JSON.parse(
	readFileSync(
		new URL('../../test/fixtures/dtcg-2025.10/format.schema.json', import.meta.url),
		'utf8'
	)
) as object;
const dtcgAjv = new Ajv({ allErrors: true, strict: true });
addFormats(dtcgAjv);
const validatesDtcg = dtcgAjv.compile(dtcgSchema);

const colors: PartialDesignSystem = {
	colors: {
		modes: [
			{
				name: 'light',
				isDefault: true,
				tokens: {
					ink: { mode: 'oklch', l: 0, c: 0, h: 0 },
				},
			},
			{
				name: 'dark',
				tokens: {
					ink: { mode: 'oklch', l: 1, c: 0, h: 0 },
				},
			},
		],
		alphaSchedule: { half: 0.5 },
	},
};

function generateHexIr() {
	return generate(colors, {
		colorFormat: { base: 'hex', alpha: 'hexa', alphaModifier: 'a' },
	});
}

describe('toFigmaJson', () => {
	it('emits valid DTCG 2025.10 color values and schema metadata', () => {
		const output = JSON.parse(
			toFigmaJson(generateHexIr(), {
				collectionName: 'Brand',
				fileHeader: { toolName: 'tfs', toolVersion: '1.2.3' },
			})
		);

		expect(output.$schema).toBe('https://www.designtokens.org/schemas/2025.10/format.json');
		expect(output.$extensions['com.three-forma-styli'].generator).toContain(
			'Generated by tfs v1.2.3'
		);
		expect(output.color.$type).toBe('color');
		expect(output.color['clr-ink'].$value).toEqual({
			colorSpace: 'srgb',
			components: [0, 0, 0],
			hex: '#000000',
		});
		expect(output.color['clr-ink-a-half'].$value).toEqual({
			colorSpace: 'srgb',
			components: [0, 0, 0],
			alpha: 0.501961,
			hex: '#000000',
		});
	});

	it('preserves color modes in a namespaced DTCG extension', () => {
		const output = JSON.parse(toFigmaJson(generateHexIr(), { collectionName: 'Brand' }));
		const extension = output.color['clr-ink'].$extensions['com.three-forma-styli'];

		expect(extension.collection).toBe('Brand');
		expect(extension.modes.light.hex).toBe('#000000');
		expect(extension.modes.dark.hex).toBe('#ffffff');
	});

	it('emits layered box/text recipes as DTCG shadow composites', () => {
		const system: PartialDesignSystem = {
			...colors,
			shadows: {
				unit: 'px',
				box: {
					elevation: {
						base: [
							{ x: 0, y: 1, blur: 3, color: { color: 'ink', alpha: 'half' } },
							{
								x: 0,
								y: 8,
								blur: 24,
								spread: -4,
								inset: true,
								color: { color: 'ink', alpha: 'half' },
							},
						],
					},
				},
				text: {
					glow: {
						base: [{ x: 0, y: 0, blur: 8, color: { color: 'ink', alpha: 'half' } }],
					},
				},
			},
		};
		const ir = generate(system, {
			colorFormat: { base: 'hex', alpha: 'hexa', alphaModifier: 'a' },
		});
		const output = JSON.parse(toFigmaJson(ir));

		expect(output.shadow.$type).toBe('shadow');
		expect(output.shadow['box-elevation'].$value).toHaveLength(2);
		expect(output.shadow['box-elevation'].$value[1]).toEqual({
			color: '{color.clr-ink-a-half}',
			offsetX: { value: 0, unit: 'px' },
			offsetY: { value: 8, unit: 'px' },
			blur: { value: 24, unit: 'px' },
			spread: { value: -4, unit: 'px' },
		});
		expect(output.shadow['box-elevation'].$extensions['com.three-forma-styli'].insetLayers).toEqual(
			[false, true]
		);
		expect(output.shadow['text-glow'].$value.spread).toEqual({
			value: 0,
			unit: 'px',
		});
		expect(output.shadow['text-glow'].$extensions['com.three-forma-styli'].kind).toBe('text');
	});

	it('emits Figma REST API color values for every mode', () => {
		const output = JSON.parse(
			toFigmaJson(
				generateHexIr(),
				{
					collectionName: 'Brand',
				},
				'figma-variables'
			)
		);
		const collection = output.collections[0];
		const ink = collection.variables.find(
			(variable: { name: string }) => variable.name === 'clr-ink'
		);

		expect(collection).toMatchObject({
			name: 'Brand',
			defaultMode: 'light',
			modes: ['light', 'dark'],
		});
		expect(ink.values.light).toEqual({
			hex: '#000000',
			rgba: { r: 0, g: 0, b: 0, a: 1 },
		});
		expect(ink.values.dark.rgba).toEqual({ r: 1, g: 1, b: 1, a: 1 });
	});

	it('labels Display-P3 components correctly without misusing CSS hex fallback', () => {
		const p3Ir = generate(colors, {
			colorFormat: { base: 'hex-p3', alpha: 'hexa-p3', alphaModifier: 'a' },
		});
		const output = JSON.parse(toFigmaJson(p3Ir, { colorSpace: 'display-p3' }));
		const value = output.color['clr-ink'].$value;

		expect(value.colorSpace).toBe('display-p3');
		expect(value.components).toHaveLength(3);
		expect(value).not.toHaveProperty('hex');
	});

	it('fails loudly when the IR is not generated in a compatible hex format', () => {
		expect(() => toFigmaJson(generate(colors))).toThrow(
			'Figma JSON requires 6- or 8-digit hex colors'
		);
	});

	it('exports standards-based dimensions without requiring a color family', () => {
		const spacingOnly = generate({
			spacing: {
				modes: [
					{
						name: 'default',
						isDefault: true,
						tokens: { unit: 'px', base: 8, min: 4, range: 2 },
					},
				],
			},
		});

		const output = JSON.parse(toFigmaJson(spacingOnly));
		expect(output).not.toHaveProperty('color');
		expect(output.dimension.$type).toBe('dimension');
		expect(output.dimension['sp-min'].$value).toEqual({ value: 4, unit: 'px' });
		expect(output.dimension['sp-2'].$value).toEqual({ value: 16, unit: 'px' });
	});

	it('exports durations, easing curves, transitions, and semantic typography composites', () => {
		const ir = generate({
			typography: {
				modes: [
					{
						name: 'default',
						isDefault: true,
						tokens: { unit: 'rem', base: 0.875, min: 0.625, increment: 0.125, range: 6 },
					},
					{
						name: 'large',
						tokens: { unit: 'rem', base: 1, min: 0.75, increment: 0.125, range: 6 },
					},
				],
				fonts: {
					sans: {
						family: 'Proof Sans',
						fallbacks: ['Arial', 'sans-serif'],
						verification: 'prepared',
						capabilities: {
							faces: [{ style: 'normal', weights: { min: 300, max: 700 } }],
						},
					},
				},
				roles: {
					prose: {
						font: 'sans',
						base: {
							fontSize: 2,
							weight: 'base',
							lineHeight: 1.25,
							letterSpacing: 0.01,
						},
						variants: {
							max: {
								fontSize: 4,
								weight: 'max',
								lineHeight: 1.1,
								letterSpacing: -0.01,
							},
						},
						modeOverrides: {
							large: { base: { lineHeight: 1.2, weight: 'max' } },
						},
						displayOrder: ['base', 'max'],
						weights: { base: 400, max: 700 },
					},
				},
			},
			time: {
				scales: [
					{
						name: 'default',
						isDefault: true,
						tokens: { unit: 'ms', base: 100, min: 50, range: 3 },
					},
				],
			},
			motion: {
				easings: { standard: [0.2, 0, 0.38, 0.9] },
				recipes: {
					hover: {
						base: { duration: 2, easing: 'standard' },
						variants: { max: { duration: 3, delay: 1 } },
					},
				},
			},
		});
		const output = JSON.parse(toFigmaJson(ir));

		expect(output.duration['t-2'].$value).toEqual({ value: 200, unit: 'ms' });
		expect(output.easing.standard.$value).toEqual([0.2, 0, 0.38, 0.9]);
		expect(output.transition['hover-max'].$value).toEqual({
			duration: { value: 300, unit: 'ms' },
			delay: { value: 100, unit: 'ms' },
			timingFunction: [0.2, 0, 0.38, 0.9],
		});
		expect(output.typography.prose.$value).toEqual({
			fontFamily: ['Proof Sans', 'Arial', 'sans-serif'],
			fontSize: { value: 1, unit: 'rem' },
			fontWeight: 400,
			letterSpacing: { value: 0.01, unit: 'rem' },
			lineHeight: 1.25,
		});
		expect(output.typography.prose.$extensions['com.three-forma-styli'].modes.large).toMatchObject({
			fontSize: { value: 1.125, unit: 'rem' },
			fontWeight: 700,
			lineHeight: 1.2,
		});
	});

	it('conforms to the pinned official DTCG 2025.10 JSON Schema', () => {
		const ir = generate(
			{
				...colors,
				spacing: {
					modes: [
						{
							name: 'default',
							isDefault: true,
							tokens: { unit: 'rem', base: 0.5, min: 0.25, range: 3 },
						},
					],
				},
				typography: {
					modes: [
						{
							name: 'default',
							isDefault: true,
							tokens: {
								unit: 'rem',
								base: 0.875,
								min: 0.625,
								increment: 0.125,
								range: 6,
							},
						},
					],
					fonts: {
						sans: {
							family: 'Proof Sans',
							fallbacks: ['Arial', 'sans-serif'],
							verification: 'prepared',
							capabilities: {
								faces: [{ style: 'normal', weights: { min: 300, max: 700 } }],
							},
						},
					},
					roles: {
						prose: {
							font: 'sans',
							base: {
								fontSize: 2,
								weight: 'base',
								lineHeight: 1.25,
								letterSpacing: 0.01,
							},
							variants: {
								max: {
									fontSize: 4,
									weight: 'max',
									lineHeight: 1.1,
									letterSpacing: -0.01,
								},
							},
							displayOrder: ['base', 'max'],
							weights: { base: 400, max: 700 },
						},
					},
				},
				time: {
					scales: [
						{
							name: 'default',
							isDefault: true,
							tokens: { unit: 'ms', base: 100, min: 50, range: 3 },
						},
					],
				},
				motion: {
					easings: { standard: [0.2, 0, 0.38, 0.9] },
					recipes: {
						hover: {
							base: { duration: 2, easing: 'standard' },
							variants: { max: { duration: 3, delay: 1 } },
						},
					},
				},
				shadows: {
					unit: 'px',
					box: {
						elevation: {
							base: [{ x: 0, y: 1, blur: 3, color: { color: 'ink', alpha: 'half' } }],
						},
					},
				},
			},
			{ colorFormat: { base: 'hex', alpha: 'hexa', alphaModifier: 'a' } }
		);
		const output = JSON.parse(toFigmaJson(ir));
		const valid = validatesDtcg(output);

		expect(valid, JSON.stringify(validatesDtcg.errors, null, 2)).toBe(true);
	});

	it('fails when an authored CSS unit has no valid DTCG composite representation', () => {
		const ir = generate(
			{
				...colors,
				shadows: {
					unit: 'em',
					box: {
						elevation: {
							base: [{ x: 0, y: 1, blur: 2, color: { color: 'ink' } }],
						},
					},
				},
			},
			{ colorFormat: { base: 'hex', alpha: 'hexa', alphaModifier: 'a' } }
		);
		expect(() => toFigmaJson(ir)).toThrow('DTCG 2025.10 dimensions support only px and rem');
	});

	it('fails rather than silently dropping a non-representable dimension family', () => {
		const ir = generate({
			spacing: {
				modes: [
					{
						name: 'default',
						isDefault: true,
						tokens: { unit: 'em', base: 1, min: 0.5, range: 2 },
					},
				],
			},
		});
		expect(() => toFigmaJson(ir)).toThrow(
			'Token --sp-min uses CSS unit "em", but DTCG 2025.10 dimensions support only px and rem'
		);
	});
});
