import type { IR, TypographyContract } from '../generator/types.js';

function variable(name: string): string {
	return `var(--${name})`;
}

function recipeManifest(recipe: TypographyContract['roles'][string]['base']) {
	return {
		fontSize: variable(recipe.fontSizeToken),
		fontWeight: variable(recipe.fontWeightToken),
		weight: recipe.weight,
		lineHeight: variable(recipe.lineHeightToken),
		letterSpacing: variable(recipe.letterSpacingToken),
		...(recipe.fontKerningToken ? { fontKerning: variable(recipe.fontKerningToken) } : {}),
		...(recipe.fontOpticalSizingToken
			? { fontOpticalSizing: variable(recipe.fontOpticalSizingToken) }
			: {}),
		...(recipe.fontFeatureSettingsToken
			? { fontFeatureSettings: variable(recipe.fontFeatureSettingsToken) }
			: {}),
		...(recipe.fontVariationSettingsToken
			? { fontVariationSettings: variable(recipe.fontVariationSettingsToken) }
			: {}),
	};
}

/** Serializable semantic typography contract shared by typed project targets. */
export function typographyContractData(contract: TypographyContract) {
	return {
		roles: Object.fromEntries(
			Object.entries(contract.roles).map(([roleName, role]) => [
				roleName,
				{
					fontFamily: variable(role.fontFamilyToken),
					defaultStyle: role.defaultStyle,
					weights: Object.fromEntries(
						Object.keys(role.weights).map((weight) => [weight, variable(role.weightTokens[weight])])
					),
					styles: Object.fromEntries(
						Object.entries(role.styles).map(([style, capability]) => [
							style,
							{
								fontStyle: capability!.value,
								weights: Object.fromEntries(
									capability!.weights.map((weight) => [weight, variable(role.weightTokens[weight])])
								),
							},
						])
					),
					base: recipeManifest(role.base),
					displayOrder: [...role.displayOrder],
					variants: Object.fromEntries(
						Object.entries(role.variants).map(([name, recipe]) => [name, recipeManifest(recipe)])
					),
				},
			])
		),
	};
}

function selectionTypes(contract: TypographyContract): string {
	const roles = Object.entries(contract.roles)
		.map(([roleName, contractRole]) => {
			const role = JSON.stringify(roleName);
			const branches = [
				`    | { role: ${role}; variant?: TypographyVariant<${role}>; fontStyle?: undefined; weight?: TypographyWeightForStyle<${role}, ${JSON.stringify(contractRole.defaultStyle)}> }`,
				...Object.keys(contractRole.styles).map(
					(style) =>
						`    | { role: ${role}; variant?: TypographyVariant<${role}>; fontStyle: ${JSON.stringify(style)}; weight: TypographyWeightForStyle<${role}, ${JSON.stringify(style)}> }`
				),
			];
			return `  ${role}:\n${branches.join('\n')};`;
		})
		.join('\n');
	return `type TypographySelectionByRole = {\n${roles}\n};\n`;
}

/** Emit a framework-neutral literal contract for consuming typography safely. */
export function toTypographyTypescript(ir: IR): string {
	if (!ir.typography || Object.keys(ir.typography.roles).length === 0) {
		throw new Error('A typography system with semantic roles is required for TypeScript output.');
	}

	const manifest = JSON.stringify(typographyContractData(ir.typography), null, 2);
	return (
		`// Generated by three-forma-styli. Do not edit.\n` +
		`export const typography = ${manifest} as const;\n\n` +
		`export type TypographyRole = keyof typeof typography.roles;\n` +
		`export type TypographyVariant<R extends TypographyRole> = keyof typeof typography.roles[R]["variants"];\n` +
		`export type TypographyWeight<R extends TypographyRole> = keyof typeof typography.roles[R]["weights"];\n` +
		`export type TypographyStyle<R extends TypographyRole> = keyof typeof typography.roles[R]["styles"];\n` +
		`export type TypographyWeightForStyle<R extends TypographyRole, S extends TypographyStyle<R>> = typeof typography.roles[R]["styles"][S] extends { readonly weights: infer W } ? keyof W : never;\n` +
		selectionTypes(ir.typography) +
		`export type TypographySelectionFor<R extends TypographyRole> = TypographySelectionByRole[R];\n` +
		`export type TypographySelection = {\n` +
		`  [R in TypographyRole]: TypographySelectionFor<R>;\n` +
		`}[TypographyRole];\n`
	);
}
