/**
 * TFS's fixed vocabulary: every position list, allowed value and generated-name
 * prefix, defined once. Types, checks and output all read from here.
 */

// ---- Position patterns ----

/** Time, Shadow, role weights. */
export const LO_HI_POSITIONS = ['min', 'lo', 'hi', 'max'] as const;
/** Alpha. Below every scale sits the fixed `non: 0`. */
export const ALPHA_POSITIONS = ['min', 'lo-x', 'lo', 'hi', 'hi-x', 'max'] as const;
/** Gap and Radius. */
export const S_L_POSITIONS = ['min', 's', 'l', 'max'] as const;
/** Role sizes; `base` is required and unsuffixed in output. */
export const ROLE_SIZE_POSITIONS = ['min', 's', 'base', 'l', 'max'] as const;

// ---- Allowed values ----

export const POLARITIES = ['negative', 'positive'] as const;
export const FONT_STYLES = ['normal', 'italic'] as const;
export const FONT_CATEGORIES = ['sans', 'serif', 'mono'] as const;
export const TEXT_TRANSFORMS = ['none', 'uppercase', 'lowercase', 'capitalize'] as const;
export const TIME_UNITS = ['ms', 's'] as const;
/** Directional shadow sets: which way the shadow falls. Down/up fall along y, left/right along x. */
export const SHADOW_DIRECTIONS = ['down', 'up', 'left', 'right'] as const;
export const LENGTH_UNITS = [
	'px',
	'rem',
	'em',
	'ch',
	'ex',
	'lh',
	'rlh',
	'vw',
	'vh',
	'vmin',
	'vmax',
	'svh',
	'lvh',
	'dvh',
	'cqw',
	'cqh',
	'cqi',
	'cqb',
	'pt',
] as const;

// ---- Generated names ----

/**
 * Every generated name starts with one of these. Opinionated and fixed for now;
 * making them configurable later means accepting overrides of this one table.
 */
export const PREFIXES = {
	alpha: 'a',
	color: 'clr',
	spacing: 'sp',
	gap: 'gap',
	radius: 'bdr',
	width: 'bdw',
	shadow: 'shd',
	time: 't',
	easing: 'ease',
	fontSize: 'fs',
	text: 'text',
} as const;

/** Typography classes share the text prefix: `.text--label-s`. */
export const TEXT_CLASS_PREFIX = `${PREFIXES.text}--`;

export const GENERATED_HEADER = '/* Generated by Three Forma Styli. Do not edit. */\n';
