import type { RuntimeColorThemeConfig } from '@three-forma-styli/core/runtime';
import { alpha } from '../alpha.js';
import { colors } from '../constraints/color.js';

// Review excerpt of the runtime-facing configuration, normally generated by TFS.
// This is not an extra hand-authored config file required of library consumers.
export const runtimeColorThemeConfig = {
	colorIdentities: ['bg', 'ev', 'pri', 'neu', 'ink'],
	alphaSchedule: { non: 0, ...alpha.scales[alpha.defaultScale].values },
	luminance: colors.constraints.luminance,
} as const satisfies RuntimeColorThemeConfig<readonly (keyof typeof colors.tokens)[]>;
